version: "3.8"

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
      POSTGRES_DB: ${POSTGRES_DB:-uride}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - .:/app:cached
    command: npm run start:dev

volumes:
  postgres_data:
